#Demo spring application

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
  - stage: 'junit Stage'
    jobs:
    - job:'JunitTest'
    displayName: 'Running Unit Tests'

steps:
  -script:echo  'Running Spring demo app unit test'
   -task:Maven@3
- task: Ant@1
  inputs:
    buildFile: 'build.xml'
    options: 
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
